/** Seed topics per conversation type slug (role-play scenarios). */
export type TopicSeed = { slug: string; title: string; description: string };

export const TOPICS_BY_TYPE_SLUG: Record<string, TopicSeed[]> = {
  'daily-life': [
    { slug: 'coffee-shop', title: 'At a Coffee Shop', description: 'Order drinks and chat with the barista.' },
    { slug: 'grocery-store', title: 'At the Grocery Store', description: 'Buy food and ask about products.' },
    { slug: 'morning-routine', title: 'Morning Routine', description: 'Talk about waking up and getting ready.' },
    { slug: 'neighborhood-walk', title: 'A Walk in the Neighborhood', description: 'Greet neighbors and describe your area.' },
    { slug: 'weather-chat', title: 'Talking About the Weather', description: 'Discuss today’s weather and plans.' },
    { slug: 'house-chores', title: 'House Chores', description: 'Describe cleaning and daily tasks at home.' },
    { slug: 'cooking-at-home', title: 'Cooking at Home', description: 'Talk about recipes and preparing meals.' },
    { slug: 'public-transport', title: 'Using Public Transport', description: 'Ask for directions and buy tickets.' },
    { slug: 'post-office', title: 'At the Post Office', description: 'Send mail and ask for services.' },
    { slug: 'bank-errands', title: 'Bank Errands', description: 'Handle simple banking conversations.' },
    { slug: 'doctor-appointment', title: 'Doctor Appointment', description: 'Describe symptoms and ask questions.' },
    { slug: 'pharmacy-visit', title: 'At the Pharmacy', description: 'Ask for medicine and advice.' },
    { slug: 'gym-session', title: 'At the Gym', description: 'Talk about exercise and fitness routines.' },
    { slug: 'weekend-plans', title: 'Weekend Plans', description: 'Discuss free time and activities.' },
    { slug: 'family-dinner', title: 'Family Dinner', description: 'Chat during a meal with family.' },
    { slug: 'pet-care', title: 'Taking Care of a Pet', description: 'Talk about feeding and walking a pet.' },
    { slug: 'lost-and-found', title: 'Lost and Found', description: 'Report or ask about a lost item.' },
    { slug: 'moving-house', title: 'Moving to a New Home', description: 'Discuss packing and settling in.' },
  ],
  'work-career': [
    { slug: 'job-interview', title: 'Job Interview', description: 'Answer common interview questions.' },
    { slug: 'first-day', title: 'First Day at Work', description: 'Meet colleagues and learn the office.' },
    { slug: 'team-meeting', title: 'Team Meeting', description: 'Share updates and ask questions.' },
    { slug: 'client-call', title: 'Client Phone Call', description: 'Handle a professional phone conversation.' },
    { slug: 'project-update', title: 'Project Update', description: 'Explain progress and next steps.' },
    { slug: 'office-lunch', title: 'Office Lunch Break', description: 'Small talk with coworkers at lunch.' },
    { slug: 'asking-help', title: 'Asking a Colleague for Help', description: 'Request assistance politely at work.' },
    { slug: 'performance-review', title: 'Performance Review', description: 'Discuss goals and feedback.' },
    { slug: 'remote-work', title: 'Working from Home', description: 'Talk about remote work routines.' },
    { slug: 'presentation', title: 'Giving a Presentation', description: 'Introduce a topic to a group.' },
    { slug: 'deadline-pressure', title: 'Meeting a Deadline', description: 'Discuss urgency and priorities.' },
    { slug: 'networking-event', title: 'Networking Event', description: 'Introduce yourself to new contacts.' },
    { slug: 'salary-discussion', title: 'Salary Discussion', description: 'Talk about compensation professionally.' },
    { slug: 'training-session', title: 'Training Session', description: 'Learn a new skill at work.' },
    { slug: 'office-conflict', title: 'Resolving a Misunderstanding', description: 'Clear up a small workplace issue.' },
  ],
  'travel-vacation': [
    { slug: 'airport-checkin', title: 'At the Airport', description: 'Check in and go through security.' },
    { slug: 'hotel-checkin', title: 'Hotel Check-in', description: 'Book a room and ask about amenities.' },
    { slug: 'asking-directions', title: 'Asking for Directions', description: 'Find your way in a new city.' },
    { slug: 'restaurant-abroad', title: 'Dining at a Restaurant', description: 'Order food while traveling.' },
    { slug: 'tourist-attraction', title: 'Visiting a Tourist Attraction', description: 'Buy tickets and ask for information.' },
    { slug: 'rental-car', title: 'Renting a Car', description: 'Pick up a vehicle and ask about rules.' },
    { slug: 'train-journey', title: 'Train Journey', description: 'Buy tickets and find your seat.' },
    { slug: 'beach-day', title: 'A Day at the Beach', description: 'Talk about sun, sand, and activities.' },
    { slug: 'souvenir-shopping', title: 'Souvenir Shopping', description: 'Buy gifts and ask about prices.' },
    { slug: 'travel-problem', title: 'Travel Problem', description: 'Handle a delay or lost item while traveling.' },
    { slug: 'local-customs', title: 'Local Customs', description: 'Learn about culture and etiquette.' },
    { slug: 'vacation-plans', title: 'Planning a Vacation', description: 'Discuss destinations and itineraries.' },
  ],
  'friends-family': [
    { slug: 'catching-up', title: 'Catching Up with a Friend', description: 'Share news and recent events.' },
    { slug: 'birthday-party', title: 'Birthday Party', description: 'Celebrate and make small talk.' },
    { slug: 'family-news', title: 'Sharing Family News', description: 'Talk about relatives and updates.' },
    { slug: 'weekend-visit', title: 'Weekend Visit', description: 'Plan a visit to friends or family.' },
    { slug: 'giving-advice', title: 'Giving Advice', description: 'Help someone with a personal decision.' },
    { slug: 'childhood-memory', title: 'Childhood Memories', description: 'Recall stories from the past.' },
    { slug: 'relationship-talk', title: 'Talking About Relationships', description: 'Discuss friendships and feelings.' },
    { slug: 'holiday-gathering', title: 'Holiday Gathering', description: 'Chat during a family celebration.' },
    { slug: 'supporting-friend', title: 'Supporting a Friend', description: 'Offer encouragement in a tough moment.' },
    { slug: 'making-plans', title: 'Making Plans Together', description: 'Agree on a time and place to meet.' },
    { slug: 'phone-call-home', title: 'Calling Home', description: 'Talk to family on the phone.' },
    { slug: 'new-baby', title: 'Welcoming a New Baby', description: 'Congratulate and ask about the family.' },
    { slug: 'housewarming', title: 'Housewarming Party', description: 'Visit someone’s new home.' },
    { slug: 'reunion', title: 'School Reunion', description: 'Meet old friends again.' },
  ],
  shopping: [
    { slug: 'clothing-store', title: 'At a Clothing Store', description: 'Try on clothes and ask for sizes.' },
    { slug: 'electronics-shop', title: 'Electronics Shop', description: 'Compare products and ask for help.' },
    { slug: 'supermarket', title: 'Supermarket Shopping', description: 'Find items and ask about prices.' },
    { slug: 'return-item', title: 'Returning an Item', description: 'Exchange or refund a purchase.' },
    { slug: 'online-order', title: 'Online Order Pickup', description: 'Collect a package and confirm details.' },
    { slug: 'bargaining-market', title: 'At the Market', description: 'Negotiate prices at a local market.' },
    { slug: 'gift-shopping', title: 'Gift Shopping', description: 'Choose a present for someone.' },
    { slug: 'shoe-store', title: 'Shoe Store', description: 'Ask about fit, style, and price.' },
    { slug: 'furniture-store', title: 'Furniture Store', description: 'Browse home items and delivery options.' },
    { slug: 'beauty-products', title: 'Beauty Products', description: 'Ask about skincare or cosmetics.' },
  ],
  'health-lifestyle': [
    { slug: 'healthy-eating', title: 'Healthy Eating', description: 'Talk about diet and nutrition.' },
    { slug: 'sleep-routine', title: 'Sleep Routine', description: 'Discuss rest and bedtime habits.' },
    { slug: 'stress-relief', title: 'Managing Stress', description: 'Share ways to relax and unwind.' },
    { slug: 'yoga-class', title: 'Yoga Class', description: 'Talk before or after a yoga session.' },
    { slug: 'running-habit', title: 'Running Habit', description: 'Discuss jogging and fitness goals.' },
    { slug: 'medical-checkup', title: 'Medical Checkup', description: 'Describe a routine health visit.' },
    { slug: 'mental-wellness', title: 'Mental Wellness', description: 'Talk about mood and self-care.' },
    { slug: 'hydration', title: 'Staying Hydrated', description: 'Discuss water intake and health.' },
    { slug: 'better-habits', title: 'Building Better Habits', description: 'Talk about improving daily lifestyle.' },
    { slug: 'allergies', title: 'Food Allergies', description: 'Explain dietary restrictions clearly.' },
    { slug: 'outdoor-activity', title: 'Outdoor Activity', description: 'Plan hiking, cycling, or sports.' },
  ],
  education: [
    { slug: 'classroom-intro', title: 'Introducing Yourself in Class', description: 'Tell classmates about yourself.' },
    { slug: 'homework-help', title: 'Homework Help', description: 'Ask a teacher or classmate for help.' },
    { slug: 'library-visit', title: 'At the Library', description: 'Find books and study resources.' },
    { slug: 'exam-prep', title: 'Exam Preparation', description: 'Discuss study plans before a test.' },
    { slug: 'group-project', title: 'Group Project', description: 'Coordinate tasks with classmates.' },
    { slug: 'university-application', title: 'University Application', description: 'Talk about applying to schools.' },
    { slug: 'language-exchange', title: 'Language Exchange', description: 'Practice with a learning partner.' },
    { slug: 'teacher-question', title: 'Asking the Teacher', description: 'Clarify a lesson or assignment.' },
    { slug: 'online-course', title: 'Online Course', description: 'Discuss learning on the internet.' },
  ],
  entertainment: [
    { slug: 'favorite-movie', title: 'Favorite Movie', description: 'Recommend films and discuss plots.' },
    { slug: 'music-taste', title: 'Music Taste', description: 'Talk about songs and artists.' },
    { slug: 'tv-series', title: 'TV Series', description: 'Discuss episodes and characters.' },
    { slug: 'concert-plan', title: 'Concert Plans', description: 'Plan to see live music.' },
    { slug: 'video-games', title: 'Video Games', description: 'Chat about games and gameplay.' },
    { slug: 'book-club', title: 'Book Club', description: 'Share opinions about a book.' },
    { slug: 'museum-visit', title: 'Museum Visit', description: 'Discuss art and exhibitions.' },
    { slug: 'sports-match', title: 'Watching a Sports Match', description: 'Talk about teams and scores.' },
    { slug: 'podcast-chat', title: 'Podcast Recommendations', description: 'Suggest shows to listen to.' },
    { slug: 'weekend-movie', title: 'Weekend Movie Night', description: 'Choose a film to watch together.' },
    { slug: 'celebrity-news', title: 'Celebrity News', description: 'Light chat about pop culture.' },
    { slug: 'theater-show', title: 'Theater Show', description: 'Discuss a play or performance.' },
  ],
};
